SHELL = /bin/sh

FLAGS = -g -std=c99 -Wall

# Funções gerais
all: 

clean:
		-rm -f *.o

purge: clean
		-rm -f 

# Construção dos executaveis
# Construção dos Objetos

# $(pkg-config allegro-5 allegro_font-5 --libs --cflags)