SHELL = /bin/sh

# Variaveis de execução
FLAGS = -g -std=c99 -Wall

ALLEGRO_LIBS = $(pkg-config allegro-5 allegro_font-5 --libs --cflags)

# Funções gerais
all: 

clean:
		-rm -f *.o

purge: clean
		-rm -f 

# Construção dos executaveis
# Construção dos Objetos